import jsPDF from 'jspdf';

export interface InvoicePdfData {
  invoiceNumber: string;
  bookingCode: string;
  customerName: string;
  businessName: string;
  items: { name: string; quantity: number; unit_price: number; total: number }[];
  subtotal: number;
  tax: number;
  discount: number;
  total: number;
  paymentStatus: string;
}

/**
 * Generates a real, downloadable PDF invoice entirely client-side — no PDF
 * generation API or server round-trip needed. Fills the "PDF generation not
 * wired yet" gap from the original invoices page.
 */
export function generateInvoicePdf(data: InvoicePdfData) {
  const doc = new jsPDF({ unit: 'pt', format: 'a4' });
  const marginX = 48;
  let y = 60;

  doc.setFontSize(18);
  doc.setTextColor(16, 129, 129);
  doc.text(data.businessName, marginX, y);

  doc.setFontSize(10);
  doc.setTextColor(120);
  y += 18;
  doc.text('ServiceFlow AI — Invoice', marginX, y);

  doc.setFontSize(11);
  doc.setTextColor(30);
  y += 34;
  doc.text(`Invoice: ${data.invoiceNumber}`, marginX, y);
  y += 16;
  doc.text(`Booking: ${data.bookingCode}`, marginX, y);
  y += 16;
  doc.text(`Billed to: ${data.customerName}`, marginX, y);
  y += 16;
  doc.text(`Payment status: ${data.paymentStatus.toUpperCase()}`, marginX, y);

  y += 32;
  doc.setDrawColor(220);
  doc.line(marginX, y, 547, y);
  y += 20;

  doc.setFontSize(10);
  doc.setTextColor(140);
  doc.text('Item', marginX, y);
  doc.text('Qty', 380, y);
  doc.text('Unit', 440, y);
  doc.text('Total', 510, y);
  y += 10;
  doc.setDrawColor(230);
  doc.line(marginX, y, 547, y);
  y += 18;

  doc.setTextColor(30);
  data.items.forEach((item) => {
    doc.text(item.name, marginX, y);
    doc.text(String(item.quantity), 380, y);
    doc.text(`$${item.unit_price.toFixed(2)}`, 440, y);
    doc.text(`$${item.total.toFixed(2)}`, 510, y);
    y += 20;
  });

  y += 12;
  doc.line(marginX, y, 547, y);
  y += 24;

  const totalsX = 420;
  doc.setTextColor(100);
  doc.text('Subtotal', totalsX, y);
  doc.text(`$${data.subtotal.toFixed(2)}`, 510, y);
  y += 16;
  doc.text('Tax', totalsX, y);
  doc.text(`$${data.tax.toFixed(2)}`, 510, y);
  y += 16;
  doc.text('Discount', totalsX, y);
  doc.text(`-$${data.discount.toFixed(2)}`, 510, y);
  y += 20;

  doc.setFontSize(13);
  doc.setTextColor(16, 129, 129);
  doc.text('Total', totalsX, y);
  doc.text(`$${data.total.toFixed(2)}`, 510, y);

  y += 60;
  doc.setFontSize(9);
  doc.setTextColor(160);
  doc.text('Generated by ServiceFlow AI', marginX, y);

  doc.save(`${data.invoiceNumber}.pdf`);
}
